# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ely.io
tagline:             'A Jekyllection'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/creativ_ely" target="_blank">@creativ_ely</a>.'
url:                 http://ely.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ely Kahn
  url:               https://twitter.com/creativ_ely
  email:             e@ely.io

# Custom vars
version:             1.2.0
